// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'ROS 2 Fundamentals',
      items: [
        'ch1-ros2-overview',
        'ch2-hands-on-ros2',
        'ch3-ai-agent-ros-bridge',
        'ch4-urdf-humanoids',
      ],
    },
    {
      type: 'category',
      label: 'Digital Twin Simulation',
      items: [
        'ch5-digital-twin-fundamentals',
        'ch6-gazebo-physics-simulation',
        'ch7-sensor-simulation',
        'ch8-unity-digital-twin',
      ],
    },
    {
      type: 'category',
      label: 'Isaac Sim VSLAM and Navigation',
      items: [
        'isaac-sim/tutorial-basics/setup',
        'isaac-sim/tutorial-basics/quick-reference',
        'isaac-sim/ch1-perception-fundamentals',
        'isaac-sim/ch2-vslam-pipeline',
        'isaac-sim/ch3-nav2-navigation',
      ],
    },
    {
      type: 'category',
      label: 'Practical Examples',
      items: [
        'examples/publisher-subscriber',
        'examples/services',
        'examples/ai-agent',
        'examples/urdf-model',
      ],
    },
  ],
};

export default sidebars;
